// Конфигурация сайта барбершопа "Барбероса"

export const siteConfig = {
  name: "Барбероса",
  tagline: "Премиальный барбершоп в Екатеринбурге",
  description: "Классические и современные мужские стрижки, моделирование бороды, королевское бритье опасной бритвой",

  contact: {
    phone: "+7 (343) 555-77-88",
    phoneRaw: "73435557788",
    whatsapp: "+7 (912) 345-67-89",
    whatsappRaw: "79123456789",
    email: "info@barbarosa-ekb.ru",
    telegram: "barbarosa_ekb",
    instagram: "@barbarosa_ekb",
    vk: "barbarosa_ekb",
    website: "barbarosa-ekb.ru",
  },

  address: {
    full: "г. Екатеринбург, ул. Вайнера, 15",
    street: "ул. Вайнера, 15",
    city: "Екатеринбург",
    metro: "Площадь 1905 года",
    metroDistance: "5 минут пешком",
    coordinates: {
      lat: 56.8389,
      lng: 60.6057,
    },
  },

  schedule: {
    weekdays: "09:00-22:00",
    weekdaysStart: "09:00",
    weekdaysEnd: "22:00",
    weekends: "10:00-21:00",
    weekendsStart: "10:00",
    weekendsEnd: "21:00",
    description: "Работаем без выходных, включая праздничные дни",
  },

  analytics: {
    ga4MeasurementId: "G-YHP1KKSYE9",
  },

  webhooks: {
    n8nProduction: "https://n8n.autopine.ru/webhook/barberosa-booking",
    n8nTest: "https://n8n.autopine.ru/webhook-test/d160150a-7119-4aa3-9375-9a2de5197026",
  },

  social: {
    instagram: "https://instagram.com/barbarosa_ekb",
    vk: "https://vk.com/barbarosa_ekb",
    telegram: "https://t.me/barbarosa_ekb",
  },

  parkingInfo: "Платная парковка на 20 мест (50 руб/час). При заказе от 2500 руб — компенсация до 2 часов",
};

export const services = [
  {
    id: "haircut-machine",
    name: "Стрижка машинкой",
    description: "Классическая мужская стрижка с\u00A0использованием машинки",
    duration: "30-40 минут",
    durationMin: 30,
    priceFrom: 800,
    priceTo: 1200,
    priceNote: "зависит от мастера",
    category: "Стрижки",
    popular: true,
  },
  {
    id: "haircut-scissors",
    name: "Стрижка ножницами",
    description: "Классическая стрижка ножницами с\u00A0детальной проработкой формы",
    duration: "45-60 минут",
    durationMin: 45,
    priceFrom: 1200,
    priceTo: 1800,
    category: "Стрижки",
    popular: true,
  },
  {
    id: "haircut-model",
    name: "Модельная стрижка",
    description: "Современные стрижки: андеркат, фейд, помпадур, квифф",
    duration: "45-60 минут",
    durationMin: 45,
    priceFrom: 1500,
    priceTo: 2200,
    category: "Стрижки",
    popular: true,
  },
  {
    id: "haircut-child",
    name: "Детская стрижка (до 12 лет)",
    description: "Стрижка для мальчиков с\u00A0опытными мастерами, игрушки и\u00A0мультики",
    duration: "30-40 минут",
    durationMin: 30,
    priceFrom: 700,
    priceTo: 900,
    category: "Стрижки",
  },
  {
    id: "haircut-teen",
    name: "Стрижка для школьников (12-16 лет)",
    description: "Современные молодежные стрижки",
    duration: "30-40 минут",
    durationMin: 30,
    priceFrom: 900,
    priceTo: 1100,
    category: "Стрижки",
  },
  {
    id: "beard-modeling",
    name: "Моделирование бороды",
    description: "Стрижка и оформление бороды с учетом формы лица",
    duration: "30-40 минут",
    durationMin: 30,
    priceFrom: 800,
    priceTo: 1200,
    category: "Борода",
    popular: true,
  },
  {
    id: "royal-shave",
    name: "Королевское бритье",
    description: "Премиальное бритье опасной бритвой с горячими полотенцами и массажем",
    duration: "45-60 минут",
    durationMin: 45,
    priceFrom: 1200,
    priceTo: 1500,
    category: "Борода",
    popular: true,
  },
  {
    id: "beard-contour",
    name: "Оформление контура бороды",
    description: "Коррекция линий и контуров бороды",
    duration: "20-30 минут",
    durationMin: 20,
    priceFrom: 500,
    priceTo: 700,
    category: "Борода",
  },
  {
    id: "head-shave",
    name: "Бритье головы",
    description: "Полное бритье головы машинкой или бритвой",
    duration: "30-40 минут",
    durationMin: 30,
    priceFrom: 800,
    priceTo: 1000,
    category: "Борода",
  },
  {
    id: "mustache",
    name: "Коррекция усов",
    description: "Оформление и стрижка усов",
    duration: "15-20 минут",
    durationMin: 15,
    priceFrom: 300,
    priceTo: 500,
    category: "Борода",
  },
  {
    id: "complex",
    name: "Комплекс (стрижка + борода)",
    description: "Полный мужской груминг: стрижка и оформление бороды",
    duration: "60-90 минут",
    durationMin: 60,
    priceFrom: 1600,
    priceTo: 3000,
    priceNote: "выгоднее на 200-400 руб",
    category: "Комплексы",
    popular: true,
    badge: "Выгодно",
  },
  {
    id: "complex-premium",
    name: "Комплекс премиум",
    description: "Стрижка + борода + королевское бритье",
    duration: "90-120 минут",
    durationMin: 90,
    priceFrom: 2800,
    priceTo: 4500,
    category: "Комплексы",
    badge: "Хит",
  },
  {
    id: "camouflage",
    name: "Камуфляж седины",
    description: "Маскировка седых волос под натуральный цвет",
    duration: "30-40 минут",
    durationMin: 30,
    priceFrom: 1500,
    priceTo: 2000,
    category: "Окрашивание",
  },
  {
    id: "beard-coloring",
    name: "Окрашивание бороды",
    description: "Окрашивание или тонирование бороды",
    duration: "30-40 минут",
    durationMin: 30,
    priceFrom: 1500,
    priceTo: 2000,
    category: "Окрашивание",
  },
  {
    id: "creative-coloring",
    name: "Креативное окрашивание",
    description: "Яркие цвета, омбре, highlights для смелых образов",
    duration: "40-60 минут",
    durationMin: 40,
    priceFrom: 2000,
    priceTo: 3000,
    category: "Окрашивание",
  },
  {
    id: "hair-toning",
    name: "Тонирование волос",
    description: "Безаммиачное тонирование для естественного оттенка",
    duration: "30-40 минут",
    durationMin: 30,
    priceFrom: 1200,
    priceTo: 1800,
    category: "Окрашивание",
  },
  {
    id: "groom-package",
    name: "Пакет «Жених»",
    description: "Модельная стрижка, борода, укладка, уход за лицом, парафинотерапия рук, напиток, фото",
    duration: "150 минут",
    durationMin: 150,
    priceFrom: 4500,
    priceTo: 4500,
    category: "Особые случаи",
    badge: "Для свадьбы",
  },
  {
    id: "business-package",
    name: "Деловой образ",
    description: "Классическая стрижка, борода, уход за лицом, маникюр для важных встреч",
    duration: "120 минут",
    durationMin: 120,
    priceFrom: 3500,
    priceTo: 3500,
    category: "Особые случаи",
  },
  {
    id: "father-son",
    name: "Отец и сын",
    description: "Стрижка для двоих: папа + сын до 12 лет, скидка 15%",
    duration: "60-90 минут",
    durationMin: 60,
    priceFrom: 1400,
    priceTo: 1800,
    category: "Особые случаи",
    badge: "Выгодно",
  },
];

export const masters = [
  {
    id: "alexey-gromov",
    name: "Алексей Громов",
    title: "Главный мастер",
    experience: "15 лет",
    specialization: "Классические стрижки, опасное бритье",
    description: "Чемпион Урала по барберингу 2023 года",
    avatar: "/masters/image5.png",
    level: "chief",
    priceAdd: 700,
  },
  {
    id: "dmitry-sokolov",
    name: "Дмитрий Соколов",
    title: "Топ-мастер",
    experience: "10 лет",
    specialization: "Современные фейды, креативные стрижки",
    description: "Специалист по сложным окрашиваниям",
    avatar: "/masters/image6.png",
    level: "top",
    priceAdd: 500,
  },
  {
    id: "ivan-petrov",
    name: "Иван Петров",
    title: "Топ-мастер",
    experience: "8 лет",
    specialization: "Бороды, моделирование, уход",
    description: "Эксперт по работе с бородой",
    avatar: "/masters/image7.png",
    level: "top",
    priceAdd: 500,
  },
  {
    id: "sergey-volkov",
    name: "Сергей Волков",
    title: "Мастер",
    experience: "5 лет",
    specialization: "Классика, деловые стрижки",
    description: "Идеален для офисного стиля",
    avatar: "/masters/image8.png",
    level: "middle",
    priceAdd: 300,
  },
  {
    id: "andrey-smirnov",
    name: "Андрей Смирнов",
    title: "Мастер",
    experience: "4 года",
    specialization: "Спортивные стрижки, детские",
    description: "Работает с детьми",
    avatar: "/masters/image9.png",
    level: "middle",
    priceAdd: 300,
  },
  {
    id: "auto",
    name: "Любой свободный мастер",
    title: "Автоподбор",
    experience: "Опытные барберы",
    specialization: "Все виды стрижек",
    description: "Свободный барбер",
    avatar: "/masters/image10.png",
    level: "middle",
    priceAdd: 0,
  },
];

export const advantages = [
  {
    title: "8 опытных мастеров",
    description: "Стаж от 3 до 15 лет, регулярное обучение",
    icon: "scissors",
  },
  {
    title: "Премиум косметика",
    description: "American Crew, Proraso, Uppercut Deluxe, Reuzel",
    icon: "cosmetics",
  },
  {
    title: "Стерильность",
    description: "Все инструменты стерилизуются после каждого клиента",
    icon: "safety",
  },
  {
    title: "Атмосфера клуба",
    description: "Винтажный интерьер 1920-х, виски-бар, PS5, библиотека",
    icon: "atmosphere",
  },
  {
    title: "В центре города",
    description: "5 минут от метро «Площадь 1905 года», парковка",
    icon: "location",
  },
  {
    title: "Без выходных",
    description: "Работаем 7 дней в неделю, удобная онлайн-запись",
    icon: "schedule",
  },
];

export const reviews = [
  {
    name: "Дмитрий К.",
    rating: 5,
    text: "Лучший барбершоп в Екатеринбурге! Алексей — мастер своего дела. Стригусь только здесь уже 2 года.",
    date: "2 недели назад",
    source: "Яндекс.Карты",
  },
  {
    name: "Максим В.",
    rating: 5,
    text: "Королевское бритье — это что-то невероятное! Расслабился так, что чуть не заснул. Кожа идеально гладкая.",
    date: "1 месяц назад",
    source: "Google",
  },
  {
    name: "Андрей С.",
    rating: 5,
    text: "Привел сына на первую стрижку. Мастера нашли подход, ребенок не плакал. Фото на память — отличная идея!",
    date: "3 недели назад",
    source: "2ГИС",
  },
];

export const awards = [
  "Лучший барбершоп Екатеринбурга 2023 (E1.ru)",
  "Топ-5 барбершопов Урала (The Village)",
  "Выбор клиентов (Бьюти-Урал 2023)",
  "Сертификат Russian Barber Association",
];

export const faqItems = [
  {
    question: "Нужна ли предварительная запись?",
    answer: "Рекомендуем записываться заранее, особенно на выходные и вечернее время. Без записи принимаем при наличии свободных мест, возможна очередь 30-60 минут.",
  },
  {
    question: "Сколько длится стрижка?",
    answer: "Стрижка машинкой — 30-40 минут, ножницами — 45-60 минут, моделирование бороды — 30-40 минут, королевское бритье — 45-60 минут, комплекс — 60-90 минут.",
  },
  {
    question: "Что входит в стрижку?",
    answer: "Консультация мастера, мытье головы профессиональным шампунем, стрижка, окантовка, укладка, массаж головы и шеи 5 минут, чай/кофе или виски на выбор.",
  },
  {
    question: "Можно ли выбрать мастера?",
    answer: "Да, при записи вы можете выбрать любого мастера. На сайте есть портфолио каждого. Цена зависит от уровня мастера: от базовой до +700 руб за главного мастера.",
  },
  {
    question: "Стрижете детей?",
    answer: "Да, специализируемся на детских стрижках для мальчиков от 1 года. Есть детское кресло-машинка, мультики, игрушки. Первая стрижка — особенный ритуал с фото.",
  },
  {
    question: "Какие есть скидки?",
    answer: "Первое посещение -15%, студентам -10% (пн-чт до 16:00), пенсионерам -15% (пн-пт до 14:00), день рождения -20%. Накопительная система: после 5 посещений -5%, после 50 — VIP-статус -15%.",
  },
  {
    question: "Как отменить запись?",
    answer: "Отмена бесплатно при уведомлении не менее чем за 3 часа. При опоздании до 15 минут примем, но время процедуры сократится. Более 30 минут — запись аннулируется.",
  },
  {
    question: "Какие способы оплаты?",
    answer: "Наличные, банковские карты (Visa, Mastercard, МИР), бесконтактная оплата (Apple Pay, Google Pay), СБП, QR-код. Оплата после услуги.",
  },
];
